id: IDF2F38A1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:55:16+00:00'
last_modified: '2022-06-07T21:14:23.622631+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7689
  title: གཡུ་དྲུག་དཀར་དཔེ་ཚོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '3624':
      image_group_id: I3CN7691
      title: ''
      total_pages: 324
      order: 1
      base_file: 3624.txt
    8AF0:
      image_group_id: I3CN7692
      title: ''
      total_pages: 256
      order: 2
      base_file: 8AF0.txt
    9DD3:
      image_group_id: I3CN7693
      title: ''
      total_pages: 300
      order: 3
      base_file: 9DD3.txt
    '3537':
      image_group_id: I3CN7694
      title: ''
      total_pages: 236
      order: 4
      base_file: 3537.txt
    6BA2:
      image_group_id: I3CN7695
      title: ''
      total_pages: 276
      order: 5
      base_file: 6BA2.txt
    DEE3:
      image_group_id: I3CN7696
      title: ''
      total_pages: 260
      order: 6
      base_file: DEE3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
