id: P004228
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7689
  title: གཡུ་དྲུག་དཀར་དཔེ་ཚོགས།
  author: ''
  volumes:
    4176d096be544868b138dd1cdcb6c97a:
      image_group_id: I3CN7691
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
    9794e46fe3ab4dd5905fabc4c3884b4c:
      image_group_id: I3CN7692
      title: ''
      volume_number: 2
      total_pages: 256
      base_file: v002.txt
    c46b4b1bcb014a979fbdd162f0d4f5e1:
      image_group_id: I3CN7693
      title: ''
      volume_number: 3
      total_pages: 300
      base_file: v003.txt
    0ab3933183a6407cbee301f448870d08:
      image_group_id: I3CN7694
      title: ''
      volume_number: 4
      total_pages: 236
      base_file: v004.txt
    49ac2103d7344ecfadec13678f4009a0:
      image_group_id: I3CN7695
      title: ''
      volume_number: 5
      total_pages: 276
      base_file: v005.txt
    2ccedb077afe4eafa9b0129b83507628:
      image_group_id: I3CN7696
      title: ''
      volume_number: 6
      total_pages: 260
      base_file: v006.txt
